/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/geodudeScene.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function GeodudeScene(props) {
  const { nodes, materials } = useGLTF("./models/geodudeScene.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-460.96, -292.72, -204.44]} // moved left 150 units * 4, down 40 units * 4
        rotation={[0.005, -0.001, -0.009]}
        scale={700.72} // scaled by 4
      >
        <mesh
          geometry={nodes.Plane.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <group
        position={[-460.8, 62.24, -697.64]} // moved left 150 units * 4, down 40 units * 4
        rotation={[-1.563, 0, 0]}
        scale={756.72} // scaled by 4
      >
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials["Material.016"]}
        />
      </group>
      <group
        position={[-653.84, 83.24, -206.32]} // moved left 150 units * 4, down 40 units * 4
        rotation={[-3.142, -0.004, 1.577]}
        scale={756.72} // scaled by 4
      >
        <mesh
          geometry={nodes.Plane002.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Plane002_1.geometry}
          material={materials["Material.013"]}
        />
      </group>
      <group position={[-394.8, -203, -324.92]} scale={52.6}>
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Cube001_2.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Cube001_3.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <group position={[-551.48, -203, -180.8]} scale={52.6}>
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Cube002_3.geometry}
          material={materials["Material.004"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/geodudeScene.glb");
